name: Build Windows EXE

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Build exe
        run: pyinstaller --onefile Main.py --name oCalc

      - name: Upload exe to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/oCalc.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
